# User config
author: "David Verweij"
tagline: "PhD Candidate at Newcastle University"
description: "Coming Soon!"
keywords: ""
email: "hi@davidverweij.com"
linkedin: "https://www.linkedin.com/in/davidverweij/"
github: "https://github.com/davidverweij"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
